### ISSUE TITLE
`UnnecessaryImport` removes star import from same package

### ISSUE THREAD

**Issue by jhonnen** [solven-eu/cleanthat#553]
Given the following class
```
package some.pkg;

import static some.pkg.ImportedClass.*;

class SomeClass {
}
```

The `UnnecessaryImport` mutator removes the star import. The cause is a subtle bug in https://github.com/solven-eu/cleanthat/blob/fa9f07330f83d5d2752b53d546b2d8739000b6b1/java/src/main/java/eu/solven/cleanthat/engine/java/refactorer/mutators/UnnecessaryImport.java#L207-L211

`getNameAsString()` for that `ImportDeclaration` returns `some.pkg.ImportedClass` and not `some.pkg.ImportedClass.*` as one could expect. Therefore the import is removed.

**Comment by jhonnen** [comment]
That was fast, thank you!

**Comment by blacelle** [comment]
2.16 is released. It may (or may not) take some hours to become available through m2central.
