### ISSUE TITLE
Unexpected warning during spotlessApply: Cannot be 'abstract' and also 'private'.

### ISSUE THREAD

**Issue by shrugalic** [solven-eu/cleanthat#807]
# Setup
We recently added `cleanthat` to our Gradle build of a Java 17 project, via [`spotless`](https://github.com/diffplug/spotless/tree/main/plugin-gradle#cleanthat) (v6.25.0):
```kts
cleanthat()
    .version("2.19")
    .sourceCompatibility("17")
    .addMutator("SafeButNotConsensual")
    .excludeMutator("UseUnderscoresInNumericLiterals")
    .excludeMutator("AvoidInlineConditionals")
```

# Issue
During a `./gradlew spotlessApply` we get the following warning:
```
> Task :server:spotlessJava
eu.solven.cleanthat.engine.java.refactorer.mutators.UnnecessaryModifier@61dd5e74 generated invalid code over cleanthat/path_is_not_available
Issue parsing some source. 1 problems. First problem: (line 60,col 3) Cannot be 'abstract' and also 'private'.
Not able to parse path='cleanthat/path_is_not_available' with com.github.javaparser.JavaParser@4a8d2db4

BUILD SUCCESSFUL in 37s
```

Unfortunately, I was unable to reproduce the issue. I did find a few `private.*abstract` things in our code base, and removed the `private` part in those, but it didn't change anything: this message still appears during a build.

**Comment by shrugalic** [comment]
Possibly related: Originally, the warning was preceded by two other lines:
```
eu.solven.cleanthat.engine.java.refactorer.mutators.UseIndexOfChar@57f566f8 generated invalid code over cleanthat/path_is_not_available
eu.solven.cleanthat.engine.java.refactorer.mutators.UnnecessaryModifier@7edec166 generated invalid code over cleanthat/path_is_not_available
```

I did find some unresolved instances of `someString.indexOf("c")` which I manually replaced with `someString.indexOf('c')`, after which the `UseIndexOfChar` line disappeared.

Similarly, I found some instances of `static` inner interfaces, from which I removed the unnecessary implicit `static` key word. I did **not** find any `public static final` methods or constants in interfaces.  Regardless of my manual changes, the `UnnecessaryModifier` line remains in the output, so it seems as if `cleanThat` thinks there is more to be found.

**Comment by blacelle** [comment]
Thanks for the report. Do you get additional details with debug logs?

**Comment by shrugalic** [comment]
> Thanks for the report. Do you get additional details with debug logs?

I just searched for how to enable debug logs in cleanThat or spotless, but was unable to find any info. Do you happen to have any pointers as to how to enable them?

**Comment by blacelle** [comment]
I would activate standard gradle debug logs.

**Comment by shrugalic** [comment]
According to [the Gradle Logging documentation](https://docs.gradle.org/current/userguide/logging.html) adding `--debug` to the `./gradlew spotlessApply` comment logs **a lot** more info (other less verbose logging levels are also available).

I'll have to spend some time filtering the 600K+ Log lines. ;)

**Comment by blacelle** [comment]
> Unfortunately, I was unable to reproduce the issue. I did find a few private.*abstract things in our code base, and removed the private part in those, but it didn't change anything: this message still appears during a build.

I wonder if cleanthat may sometimes produce such invalid code, but it is not persisted due to the fact the output code would be invalid,

**Comment by blacelle** [comment]
In normal logs, do you see files modified by `UnnecessaryModifier` ?

**Comment by shrugalic** [comment]
Hmm, it appears I'm somewhat consistently able to reproduce the issue.

In my case I created this example of unnecessary `public static final` modifiers:
```java
public class Sample {
	public static interface TestInterface {
		public static final String TEST_CONSTANT = "test";
	}
}
```

With this, I got this message:
```
> Task :server:spotlessJava
eu.solven.cleanthat.engine.java.refactorer.mutators.UnnecessaryModifier@4f71e78d generated invalid code over cleanthat/path_is_not_available
Issue parsing some source. 1 problems. First problem: (line 60,col 3) Cannot be 'abstract' and also 'private'.
Not able to parse path='cleanthat/path_is_not_available' with com.github.javaparser.JavaParser@276ae05c
```

Despite the error message, the code _is_ cleaned up, and the next time the message will **not** re-appear.

**Comment by shrugalic** [comment]
> I wonder if cleanthat may sometimes produce such invalid code, but it is not persisted due to the fact the output code would be invalid

That seems very plausible indeed.

> In normal logs, do you see files modified by `UnnecessaryModifier`?

Yes. Like you wrote, I assume there are still issues it would want to fix, but can't, and does not persist anything.

Issues it can fix are fixed, such as the sample in my previous comment.

**Comment by blacelle** [comment]
Thanks for the details. I'll make a new release very soon.

**Comment by blacelle** [comment]
This is fixed in Cleanthat 2.20. Thanks a lot for the report and the investigation.

**Comment by shrugalic** [comment]
Thanks. It seems [v2.20 was released](https://github.com/solven-eu/cleanthat/tags), but [without listing the changes](https://github.com/solven-eu/cleanthat/blob/master/CHANGES.MD).

**Comment by shrugalic** [comment]
With the new version, I get this message:
```
> Task :server:spotlessJava
eu.solven.cleanthat.engine.java.refactorer.mutators.UnnecessaryModifier@655a1146 generated invalid code over cleanthat/path_is_not_available
```

where previously I got this:
```
> Task :server:spotlessJava
eu.solven.cleanthat.engine.java.refactorer.mutators.UnnecessaryModifier@7c656082 generated invalid code over cleanthat/path_is_not_available
Issue parsing some source. 1 problems. First problem: (line 60,col 3) Cannot be 'abstract' and also 'private'.
Not able to parse path='cleanthat/path_is_not_available' with com.github.javaparser.JavaParser@1a24d83f
```

**Comment by blacelle** [comment]
@shrugalic Have you been able to identity the faulty file? If yes, could you provide it? Thanks

**Comment by shrugalic** [comment]
I have not.

**Comment by blacelle** [comment]
The lack of proper file path in logs was related to Spotless integration. An upcoming Spotless release should make it much easier to get which file is faulty.

**Comment by shrugalic** [comment]
Current state of affairs AFAICS:
- Spotless 7.0 will propagate better error messages from CleanChat, but is not final yet ([CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md))
- The better error messages are part of CleanThat v2.20 (which seems to be missing from its own [CHANGES.md](https://github.com/solven-eu/cleanthat/blob/master/CHANGES.MD))

**Comment by blacelle** [comment]
Could you have a try with Spotless.7.0 even in BETA, as it may provide enough information to find the underlying cleanthat issue?

**Comment by shrugalic** [comment]
@blacelle: What version of cleanthat would I enter into my build files? As mentioned there are no versions newer than 2.20 listed in the cleanthat change log. When I try 2.21 like so:
```kts
cleanthat()
    .version("2.21")
    .sourceCompatibility(javaVersion.toString())
    .addMutator("SafeButNotConsensual")
    .excludeMutator("UseUnderscoresInNumericLiterals")
    .excludeMutator("AvoidInlineConditionals")
endWithNewline()
indentWithTabs()
trimTrailingWhitespace()
encoding("UTF-8")
toggleOffOn("@formatter:off", "@formatter:on")
```
it gives a build error:
```
16: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':spotlessJava'.
> You need to add a repository containing the '[io.github.solven-eu.cleanthat:java:2.21]' artifact in 'build.gradle'.
  E.g.: 'repositories { mavenCentral() }'
  ```

**Comment by blacelle** [comment]
Oh nice. Given you reported `eu.solven.cleanthat.engine.java.refactorer.mutators.UnnecessaryModifier@30add310 generated invalid code over <path/to/the/following/file>`, I thought the actual file path was still not reported.

Thanks for the validation, and sorry for the friction in fixing it.

Regarding the `UnnecessaryModifier` issue o nyour case, I do not foresee why it happens, but I hope your case will help me understand what's wrong so I can fix it.

**Comment by shrugalic** [comment]
The file path _was_ indeed reported, I just replaced it with something that didn't reveal information I didn't want it to. ;)

I hope the file I posted helps reproduce the issue. Maybe the unnecessary-modifier-removal-code has issues with the extra annotations in this case.

**Comment by blacelle** [comment]
Mmm. This was due to some JavaParser issue. Post-modification, the source is like:

```                                                                                                                                      
public interface Issue807 {                                                                                                                                                                                                                                                                                     
	 @ValidList<AccountRef> getAccount();                                                                                                                                                                                                                                           
}
```

I'll try to workaround it within cleanthat, at it seems related with https://github.com/javaparser/javaparser/issues/3935
