### ISSUE TITLE
Error parsing switch over sealed type

### ISSUE THREAD

**Issue by shrugalic** [solven-eu/cleanthat#817]
We recently upgraded from Java 17 to Java 21. Apparently the JavaParser has a problem with `switch` over a sealed type.

- spotless 6.25.0 or 7.0.0.BETA1
- cleanthat 2.20

##### Error message and partial stack trace
```
> Task :server:spotlessJava
Issue parsing some source. 2 problems. First problem: (line 19,col 9) Parse error. Found  "pSim" <IDENTIFIER>, expected one of  "!=" "%" "&" "&&" "(" "*" "+" "," "-" "->" "/" ":" "<" "<=" "==" ">" ">=" "?" "^" "instanceof" "|" "||"
Problem stacktrace :
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:14041)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:13886)
  com.github.javaparser.GeneratedJavaParser.SwitchEntry(GeneratedJavaParser.java:6443)
  com.github.javaparser.GeneratedJavaParser.SwitchStatement(GeneratedJavaParser.java:6233)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:5683)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:5933)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:2795)
  com.github.javaparser.GeneratedJavaParser.ConstructorDeclaration(GeneratedJavaParser.java:2632)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1752)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:1281)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:538)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:156)
  com.github.javaparser.JavaParser.parse(JavaParser.java:125)
  com.github.javaparser.JavaParser.parse(JavaParser.java:305)
  eu.solven.cleanthat.engine.java.refactorer.JavaRefactorer.parseSourceCode(JavaRefactorer.java:105)
  eu.solven.cleanthat.engine.java.refactorer.JavaRefactorer.parseSourceCode(JavaRefactorer.java:63)
  eu.solven.cleanthat.engine.java.refactorer.AstRefactorerInstance.parseCompilationUnit(AstRefactorerInstance.java:136)
  eu.solven.cleanthat.engine.java.refactorer.AstRefactorerInstance.applyOneMutator(AstRefactorerInstance.java:72)
  eu.solven.cleanthat.engine.java.refactorer.AAstRefactorer.lambda$applyTransformers$2(AAstRefactorer.java:130
…
  ```

##### Code
The code in question looks something like this:
```java
switch (sim) {
	case PhysicalSimCard pSim -> doPSimStuff(); // <-- This must be the line in the error message
	case ESim eSim -> doESimStuff();
}

public sealed interface Sim permits PhysicalSimCard, ESim {
	// methods
}

record PhysicalSimCard() {}

record ESim() {}
```

PS: Not sure if this is the right place for this report, or if I should move it to https://github.com/javaparser/javaparser instead.

**Comment by blacelle** [comment]
Could you try indicating JDK21 source code explicitly:
```
    cleanthat()
      .version('2.20') 
      .sourceCompatibility('21')
```
?

**Comment by shrugalic** [comment]
We already do that.

**Comment by shrugalic** [comment]
PS: This also happens with spotless 7.0.0.BETA1

**Comment by Jallibad** [comment]
I think the problem is the dependency on [`com.github.javaparser:javaparser-symbol-solver-core:3.25.10`](https://github.com/solven-eu/cleanthat/blob/v2.20.RELEASE/java/pom.xml#L38). [`3.26.0`](https://github.com/javaparser/javaparser/releases/tag/javaparser-parent-3.26.0) brings support for record patterns. Would it be possible to bump that dependency?

**Comment by blacelle** [comment]
Updated the dependency did not fix the issue

**Comment by Jallibad** [comment]
Updating the dependency did fix the issue for me. Updating it while using Spotless was a bit hacky though, I had to add a `ComponentMetadataRule` to do so. IIRC there are still some Java 21 pattern matching related features that are not supported by the newer version of the dependency but it is now able to parse pattern matches for me.

**Comment by blacelle** [comment]
`cleanthat:2.21` has been released over `javaparser:3.26.1`.

I believe I mis-reported the issue as not being fixed as I was considering a different issue while checking an upgraded `javaparser`.

**Comment by shrugalic** [comment]
🙏 Thanks a lot you two, I can confirm the the problem no longer occurs with cleanthat v2.21.

**Comment by shrugalic** [comment]
PS: I should have been more specific. What is solved is the original issue with switching over types.

The [secondary issue](https://github.com/solven-eu/cleanthat/issues/817#issuecomment-2236153548) still happens. I'll open a new ticket for that.
